language: python
notifications:
  email: false
python:
  - "3.6.0"
  - "3.6.1"
  - "3.6.3"
  - "3.6.5"
  - "3.6.6"
  - "3.6.7"

install:
  - pip install -r requirements.txt
env:
  global:
    - CONSUMER_KEY=X
    - CONSUMER_SECRET=X
    - ACCESS_TOKEN=X-X
    - ACCESS_TOKEN_SECRET=X
  matrix:
    - TOXENV=py
jobs:
  include:
    - python: 3.6.6
      env: TOXENV=style
script:
  - python -m unittest discover -s tests/test_config
  - python -m unittest discover -s tests/test_options
  - python -m unittest discover -s tests/test_discord
  - python -m unittest discover -s tests/test_python
