dist: xenial
language: python
cache: pip
notifications:
  email: false
python:
  - "3.6.6"
  - "3.6.7"

install:
  - pip install -r requirements.txt
env:
  global:
    - CONSUMER_KEY=X
    - CONSUMER_SECRET=X
    - ACCESS_TOKEN=X-X
    - ACCESS_TOKEN_SECRET=X
jobs:
  include:
    - python: 3.6.6
      name: "Stylecheck"
      script: black --check --diff -l 99 -N `git ls-files "*.py"`
script:
  - python -m unittest discover -s tests/test_config
  - python -m unittest discover -s tests/test_options
  - python -m unittest discover -s tests/test_discord
  - python -m unittest discover -s tests/test_python
